name: ssapick-docker-compose
version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8000:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  database:
    image: postgres:16.3-alpine
    container_name: ssapick-database
    environment:
      POSTGRES_USER: ssapick
      POSTGRES_PASSWORD: ssapick
      POSTGRES_DB: ssapick
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  database-admin:
    container_name: database-admin
    image: dpage/pgadmin4
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "ssapick@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "ssapick"
    restart: always

  cache-database:
    image: redis:7.4-rc2-alpine
    container_name: ssapick-cache-database
    ports:
      - "6379:6379"
    entrypoint: redis-server --requirepass ssapick --maxmemory 128mb

  korean_sentence_similarity:
    image : ssafysm/ssapick_fast_api:1.3
    container_name: ssapick-korean-sentence-similarity
    ports:
      - "2252:2252"
